/* Automatically generated by tree-sitter v0.25.1 (f5afe475deb7c0bae6407fb776c76824f717bb61) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 36
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 1
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_code_token1 = 1,
  anon_sym_PERCENT_PERCENT_GT = 2,
  aux_sym_content_token1 = 3,
  anon_sym_LT_PERCENT_PERCENT = 4,
  anon_sym_LT_QMARK = 5,
  anon_sym_LT_PERCENT = 6,
  anon_sym_LT_PERCENT_ = 7,
  anon_sym_LT_PERCENT_PIPE = 8,
  anon_sym_PERCENT_GT = 9,
  anon_sym_DASH_PERCENT_GT = 10,
  anon_sym__PERCENT_GT = 11,
  anon_sym_LT_QMARK_EQ = 12,
  anon_sym_LT_PERCENT_EQ = 13,
  anon_sym_LT_PERCENT_EQ_EQ = 14,
  anon_sym_LT_PERCENT_PIPE_EQ = 15,
  anon_sym_LT_PERCENT_PIPE_EQ_EQ = 16,
  anon_sym_LT_PERCENT_DASH = 17,
  anon_sym_QMARK_GT = 18,
  anon_sym_EQ_PERCENT_GT = 19,
  anon_sym_LT_PERCENT_POUND = 20,
  anon_sym_LT_PERCENTgraphql = 21,
  anon_sym_LT_QMARKphp = 22,
  sym_template = 23,
  sym_code = 24,
  sym_content = 25,
  sym_directive = 26,
  sym_output_directive = 27,
  sym_comment_directive = 28,
  sym_graphql_directive = 29,
  sym_php_directive = 30,
  aux_sym_template_repeat1 = 31,
  aux_sym_code_repeat1 = 32,
  aux_sym_content_repeat1 = 33,
  alias_sym_comment = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_code_token1] = "code_token1",
  [anon_sym_PERCENT_PERCENT_GT] = "%%>",
  [aux_sym_content_token1] = "content_token1",
  [anon_sym_LT_PERCENT_PERCENT] = "<%%",
  [anon_sym_LT_QMARK] = "<\?",
  [anon_sym_LT_PERCENT] = "<%",
  [anon_sym_LT_PERCENT_] = "<%_",
  [anon_sym_LT_PERCENT_PIPE] = "<%|",
  [anon_sym_PERCENT_GT] = "%>",
  [anon_sym_DASH_PERCENT_GT] = "-%>",
  [anon_sym__PERCENT_GT] = "_%>",
  [anon_sym_LT_QMARK_EQ] = "<\?=",
  [anon_sym_LT_PERCENT_EQ] = "<%=",
  [anon_sym_LT_PERCENT_EQ_EQ] = "<%==",
  [anon_sym_LT_PERCENT_PIPE_EQ] = "<%|=",
  [anon_sym_LT_PERCENT_PIPE_EQ_EQ] = "<%|==",
  [anon_sym_LT_PERCENT_DASH] = "<%-",
  [anon_sym_QMARK_GT] = "\?>",
  [anon_sym_EQ_PERCENT_GT] = "=%>",
  [anon_sym_LT_PERCENT_POUND] = "<%#",
  [anon_sym_LT_PERCENTgraphql] = "<%graphql",
  [anon_sym_LT_QMARKphp] = "<\?php",
  [sym_template] = "template",
  [sym_code] = "code",
  [sym_content] = "content",
  [sym_directive] = "directive",
  [sym_output_directive] = "output_directive",
  [sym_comment_directive] = "comment_directive",
  [sym_graphql_directive] = "graphql_directive",
  [sym_php_directive] = "php_directive",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_code_repeat1] = "code_repeat1",
  [aux_sym_content_repeat1] = "content_repeat1",
  [alias_sym_comment] = "comment",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_code_token1] = aux_sym_code_token1,
  [anon_sym_PERCENT_PERCENT_GT] = anon_sym_PERCENT_PERCENT_GT,
  [aux_sym_content_token1] = aux_sym_content_token1,
  [anon_sym_LT_PERCENT_PERCENT] = anon_sym_LT_PERCENT_PERCENT,
  [anon_sym_LT_QMARK] = anon_sym_LT_QMARK,
  [anon_sym_LT_PERCENT] = anon_sym_LT_PERCENT,
  [anon_sym_LT_PERCENT_] = anon_sym_LT_PERCENT_,
  [anon_sym_LT_PERCENT_PIPE] = anon_sym_LT_PERCENT_PIPE,
  [anon_sym_PERCENT_GT] = anon_sym_PERCENT_GT,
  [anon_sym_DASH_PERCENT_GT] = anon_sym_DASH_PERCENT_GT,
  [anon_sym__PERCENT_GT] = anon_sym__PERCENT_GT,
  [anon_sym_LT_QMARK_EQ] = anon_sym_LT_QMARK_EQ,
  [anon_sym_LT_PERCENT_EQ] = anon_sym_LT_PERCENT_EQ,
  [anon_sym_LT_PERCENT_EQ_EQ] = anon_sym_LT_PERCENT_EQ_EQ,
  [anon_sym_LT_PERCENT_PIPE_EQ] = anon_sym_LT_PERCENT_PIPE_EQ,
  [anon_sym_LT_PERCENT_PIPE_EQ_EQ] = anon_sym_LT_PERCENT_PIPE_EQ_EQ,
  [anon_sym_LT_PERCENT_DASH] = anon_sym_LT_PERCENT_DASH,
  [anon_sym_QMARK_GT] = anon_sym_QMARK_GT,
  [anon_sym_EQ_PERCENT_GT] = anon_sym_EQ_PERCENT_GT,
  [anon_sym_LT_PERCENT_POUND] = anon_sym_LT_PERCENT_POUND,
  [anon_sym_LT_PERCENTgraphql] = anon_sym_LT_PERCENTgraphql,
  [anon_sym_LT_QMARKphp] = anon_sym_LT_QMARKphp,
  [sym_template] = sym_template,
  [sym_code] = sym_code,
  [sym_content] = sym_content,
  [sym_directive] = sym_directive,
  [sym_output_directive] = sym_output_directive,
  [sym_comment_directive] = sym_comment_directive,
  [sym_graphql_directive] = sym_graphql_directive,
  [sym_php_directive] = sym_php_directive,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_code_repeat1] = aux_sym_code_repeat1,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
  [alias_sym_comment] = alias_sym_comment,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_code_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PERCENT_PERCENT_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT_PERCENT_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_PERCENT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__PERCENT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_QMARK_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_PIPE_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_PIPE_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_PERCENT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENTgraphql] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_QMARKphp] = {
    .visible = true,
    .named = false,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_output_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_graphql_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_php_directive] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_comment] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_comment,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_code, 2,
    sym_code,
    alias_sym_comment,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 19,
  [22] = 20,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 19,
  [27] = 27,
  [28] = 20,
  [29] = 19,
  [30] = 20,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(19);
      if (lookahead == '%') ADVANCE(22);
      if (lookahead == '-') ADVANCE(25);
      if (lookahead == '<') ADVANCE(23);
      if (lookahead == '=') ADVANCE(26);
      if (lookahead == '?') ADVANCE(29);
      if (lookahead == '_') ADVANCE(27);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 1:
      if (lookahead == '%') ADVANCE(22);
      if (lookahead == '-') ADVANCE(25);
      if (lookahead == '=') ADVANCE(26);
      if (lookahead == '?') ADVANCE(29);
      if (lookahead == '_') ADVANCE(20);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 2:
      if (lookahead == '%') ADVANCE(22);
      if (lookahead == '-') ADVANCE(25);
      if (lookahead == '_') ADVANCE(27);
      if (lookahead == '=' ||
          lookahead == '?') ADVANCE(20);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 3:
      if (lookahead == '%') ADVANCE(22);
      if (lookahead == '-' ||
          lookahead == '=' ||
          lookahead == '?' ||
          lookahead == '_') ADVANCE(20);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 4:
      if (lookahead == '%') ADVANCE(21);
      if (lookahead == '?') ADVANCE(29);
      if (lookahead == '-' ||
          lookahead == '=' ||
          lookahead == '_') ADVANCE(20);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(33);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(44);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(54);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(45);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'h') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'h') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(56);
      END_STATE();
    case 13:
      if (lookahead == 'p') ADVANCE(57);
      END_STATE();
    case 14:
      if (lookahead == 'p') ADVANCE(11);
      END_STATE();
    case 15:
      if (lookahead == 'q') ADVANCE(12);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 17:
      if (eof) ADVANCE(19);
      if (lookahead == '%') ADVANCE(24);
      if (lookahead == '<') ADVANCE(23);
      if (lookahead == '?') ADVANCE(30);
      if (lookahead == '-' ||
          lookahead == '=' ||
          lookahead == '_') ADVANCE(32);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 18:
      if (eof) ADVANCE(19);
      if (lookahead == '<') ADVANCE(35);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_code_token1);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '%') ADVANCE(5);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '%') ADVANCE(5);
      if (lookahead == '>') ADVANCE(43);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '%') ADVANCE(40);
      if (lookahead == '?') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '-' &&
          lookahead != '=' &&
          lookahead != '_') ADVANCE(31);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '%') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(37);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '%') ADVANCE(6);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '%') ADVANCE(7);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '%') ADVANCE(8);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '<') ADVANCE(31);
      if (lookahead == '%' ||
          lookahead == '-' ||
          lookahead == '=' ||
          lookahead == '?' ||
          lookahead == '_') ADVANCE(37);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '>') ADVANCE(52);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '>') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(37);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead != 0 &&
          lookahead != '%' &&
          lookahead != '-' &&
          lookahead != '=' &&
          lookahead != '?' &&
          lookahead != '_') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(37);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PERCENT_PERCENT_GT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_PERCENT_PERCENT_GT);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead == '%') ADVANCE(40);
      if (lookahead == '?') ADVANCE(39);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead == '>') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_PERCENT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LT_QMARK);
      if (lookahead == '=') ADVANCE(46);
      if (lookahead == 'p') ADVANCE(10);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT);
      if (lookahead == '#') ADVANCE(55);
      if (lookahead == '%') ADVANCE(38);
      if (lookahead == '-') ADVANCE(51);
      if (lookahead == '=') ADVANCE(47);
      if (lookahead == '_') ADVANCE(41);
      if (lookahead == 'g') ADVANCE(16);
      if (lookahead == '|') ADVANCE(42);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_PIPE);
      if (lookahead == '=') ADVANCE(49);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_PERCENT_GT);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_DASH_PERCENT_GT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym__PERCENT_GT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LT_QMARK_EQ);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_EQ);
      if (lookahead == '=') ADVANCE(48);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_EQ_EQ);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_PIPE_EQ);
      if (lookahead == '=') ADVANCE(50);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_PIPE_EQ_EQ);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_DASH);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_QMARK_GT);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_QMARK_GT);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(37);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_EQ_PERCENT_GT);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_POUND);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LT_PERCENTgraphql);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LT_QMARKphp);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 18},
  [2] = {.lex_state = 18},
  [3] = {.lex_state = 18},
  [4] = {.lex_state = 17},
  [5] = {.lex_state = 18},
  [6] = {.lex_state = 18},
  [7] = {.lex_state = 18},
  [8] = {.lex_state = 18},
  [9] = {.lex_state = 18},
  [10] = {.lex_state = 18},
  [11] = {.lex_state = 18},
  [12] = {.lex_state = 18},
  [13] = {.lex_state = 18},
  [14] = {.lex_state = 18},
  [15] = {.lex_state = 18},
  [16] = {.lex_state = 18},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_code_token1] = ACTIONS(1),
    [anon_sym_PERCENT_PERCENT_GT] = ACTIONS(1),
    [anon_sym_LT_PERCENT_PERCENT] = ACTIONS(1),
    [anon_sym_LT_QMARK] = ACTIONS(1),
    [anon_sym_LT_PERCENT] = ACTIONS(1),
    [anon_sym_LT_PERCENT_] = ACTIONS(1),
    [anon_sym_LT_PERCENT_PIPE] = ACTIONS(1),
    [anon_sym_PERCENT_GT] = ACTIONS(1),
    [anon_sym_DASH_PERCENT_GT] = ACTIONS(1),
    [anon_sym__PERCENT_GT] = ACTIONS(1),
    [anon_sym_LT_QMARK_EQ] = ACTIONS(1),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(1),
    [anon_sym_LT_PERCENT_EQ_EQ] = ACTIONS(1),
    [anon_sym_LT_PERCENT_PIPE_EQ] = ACTIONS(1),
    [anon_sym_LT_PERCENT_PIPE_EQ_EQ] = ACTIONS(1),
    [anon_sym_LT_PERCENT_DASH] = ACTIONS(1),
    [anon_sym_QMARK_GT] = ACTIONS(1),
    [anon_sym_EQ_PERCENT_GT] = ACTIONS(1),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(1),
    [anon_sym_LT_PERCENTgraphql] = ACTIONS(1),
    [anon_sym_LT_QMARKphp] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_template] = STATE(34),
    [sym_content] = STATE(2),
    [sym_directive] = STATE(2),
    [sym_output_directive] = STATE(2),
    [sym_comment_directive] = STATE(2),
    [sym_graphql_directive] = STATE(2),
    [sym_php_directive] = STATE(2),
    [aux_sym_template_repeat1] = STATE(2),
    [aux_sym_content_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_content_token1] = ACTIONS(5),
    [anon_sym_LT_PERCENT_PERCENT] = ACTIONS(7),
    [anon_sym_LT_QMARK] = ACTIONS(9),
    [anon_sym_LT_PERCENT] = ACTIONS(11),
    [anon_sym_LT_PERCENT_] = ACTIONS(13),
    [anon_sym_LT_PERCENT_PIPE] = ACTIONS(11),
    [anon_sym_LT_QMARK_EQ] = ACTIONS(15),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(17),
    [anon_sym_LT_PERCENT_EQ_EQ] = ACTIONS(15),
    [anon_sym_LT_PERCENT_PIPE_EQ] = ACTIONS(17),
    [anon_sym_LT_PERCENT_PIPE_EQ_EQ] = ACTIONS(15),
    [anon_sym_LT_PERCENT_DASH] = ACTIONS(15),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(19),
    [anon_sym_LT_PERCENTgraphql] = ACTIONS(21),
    [anon_sym_LT_QMARKphp] = ACTIONS(23),
  },
  [STATE(2)] = {
    [sym_content] = STATE(3),
    [sym_directive] = STATE(3),
    [sym_output_directive] = STATE(3),
    [sym_comment_directive] = STATE(3),
    [sym_graphql_directive] = STATE(3),
    [sym_php_directive] = STATE(3),
    [aux_sym_template_repeat1] = STATE(3),
    [aux_sym_content_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(25),
    [aux_sym_content_token1] = ACTIONS(5),
    [anon_sym_LT_PERCENT_PERCENT] = ACTIONS(7),
    [anon_sym_LT_QMARK] = ACTIONS(9),
    [anon_sym_LT_PERCENT] = ACTIONS(11),
    [anon_sym_LT_PERCENT_] = ACTIONS(13),
    [anon_sym_LT_PERCENT_PIPE] = ACTIONS(11),
    [anon_sym_LT_QMARK_EQ] = ACTIONS(15),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(17),
    [anon_sym_LT_PERCENT_EQ_EQ] = ACTIONS(15),
    [anon_sym_LT_PERCENT_PIPE_EQ] = ACTIONS(17),
    [anon_sym_LT_PERCENT_PIPE_EQ_EQ] = ACTIONS(15),
    [anon_sym_LT_PERCENT_DASH] = ACTIONS(15),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(19),
    [anon_sym_LT_PERCENTgraphql] = ACTIONS(21),
    [anon_sym_LT_QMARKphp] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym_content] = STATE(3),
    [sym_directive] = STATE(3),
    [sym_output_directive] = STATE(3),
    [sym_comment_directive] = STATE(3),
    [sym_graphql_directive] = STATE(3),
    [sym_php_directive] = STATE(3),
    [aux_sym_template_repeat1] = STATE(3),
    [aux_sym_content_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(27),
    [aux_sym_content_token1] = ACTIONS(29),
    [anon_sym_LT_PERCENT_PERCENT] = ACTIONS(32),
    [anon_sym_LT_QMARK] = ACTIONS(35),
    [anon_sym_LT_PERCENT] = ACTIONS(38),
    [anon_sym_LT_PERCENT_] = ACTIONS(41),
    [anon_sym_LT_PERCENT_PIPE] = ACTIONS(38),
    [anon_sym_LT_QMARK_EQ] = ACTIONS(44),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(47),
    [anon_sym_LT_PERCENT_EQ_EQ] = ACTIONS(44),
    [anon_sym_LT_PERCENT_PIPE_EQ] = ACTIONS(47),
    [anon_sym_LT_PERCENT_PIPE_EQ_EQ] = ACTIONS(44),
    [anon_sym_LT_PERCENT_DASH] = ACTIONS(44),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(50),
    [anon_sym_LT_PERCENTgraphql] = ACTIONS(53),
    [anon_sym_LT_QMARKphp] = ACTIONS(56),
  },
  [STATE(4)] = {
    [sym_code] = STATE(32),
    [aux_sym_code_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(59),
    [aux_sym_code_token1] = ACTIONS(61),
    [anon_sym_PERCENT_PERCENT_GT] = ACTIONS(61),
    [aux_sym_content_token1] = ACTIONS(63),
    [anon_sym_LT_PERCENT_PERCENT] = ACTIONS(59),
    [anon_sym_LT_QMARK] = ACTIONS(63),
    [anon_sym_LT_PERCENT] = ACTIONS(63),
    [anon_sym_LT_PERCENT_] = ACTIONS(59),
    [anon_sym_LT_PERCENT_PIPE] = ACTIONS(63),
    [anon_sym_LT_QMARK_EQ] = ACTIONS(59),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(63),
    [anon_sym_LT_PERCENT_EQ_EQ] = ACTIONS(59),
    [anon_sym_LT_PERCENT_PIPE_EQ] = ACTIONS(63),
    [anon_sym_LT_PERCENT_PIPE_EQ_EQ] = ACTIONS(59),
    [anon_sym_LT_PERCENT_DASH] = ACTIONS(59),
    [anon_sym_QMARK_GT] = ACTIONS(65),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(59),
    [anon_sym_LT_PERCENTgraphql] = ACTIONS(59),
    [anon_sym_LT_QMARKphp] = ACTIONS(59),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(71), 1,
      anon_sym_LT_PERCENT_PERCENT,
    STATE(6), 1,
      aux_sym_content_repeat1,
    ACTIONS(69), 2,
      aux_sym_content_token1,
      anon_sym_LT_QMARK,
    ACTIONS(73), 4,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_PIPE,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ,
    ACTIONS(67), 9,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_,
      anon_sym_LT_QMARK_EQ,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ_EQ,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENTgraphql,
      anon_sym_LT_QMARKphp,
  [28] = 5,
    ACTIONS(80), 1,
      anon_sym_LT_PERCENT_PERCENT,
    STATE(6), 1,
      aux_sym_content_repeat1,
    ACTIONS(77), 2,
      aux_sym_content_token1,
      anon_sym_LT_QMARK,
    ACTIONS(83), 4,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_PIPE,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ,
    ACTIONS(75), 9,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_,
      anon_sym_LT_QMARK_EQ,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ_EQ,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENTgraphql,
      anon_sym_LT_QMARKphp,
  [56] = 2,
    ACTIONS(87), 6,
      aux_sym_content_token1,
      anon_sym_LT_QMARK,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_PIPE,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ,
    ACTIONS(85), 10,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_PERCENT,
      anon_sym_LT_PERCENT_,
      anon_sym_LT_QMARK_EQ,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ_EQ,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENTgraphql,
      anon_sym_LT_QMARKphp,
  [77] = 2,
    ACTIONS(91), 6,
      aux_sym_content_token1,
      anon_sym_LT_QMARK,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_PIPE,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ,
    ACTIONS(89), 10,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_PERCENT,
      anon_sym_LT_PERCENT_,
      anon_sym_LT_QMARK_EQ,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ_EQ,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENTgraphql,
      anon_sym_LT_QMARKphp,
  [98] = 2,
    ACTIONS(95), 6,
      aux_sym_content_token1,
      anon_sym_LT_QMARK,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_PIPE,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ,
    ACTIONS(93), 10,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_PERCENT,
      anon_sym_LT_PERCENT_,
      anon_sym_LT_QMARK_EQ,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ_EQ,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENTgraphql,
      anon_sym_LT_QMARKphp,
  [119] = 2,
    ACTIONS(99), 6,
      aux_sym_content_token1,
      anon_sym_LT_QMARK,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_PIPE,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ,
    ACTIONS(97), 10,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_PERCENT,
      anon_sym_LT_PERCENT_,
      anon_sym_LT_QMARK_EQ,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ_EQ,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENTgraphql,
      anon_sym_LT_QMARKphp,
  [140] = 2,
    ACTIONS(103), 6,
      aux_sym_content_token1,
      anon_sym_LT_QMARK,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_PIPE,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ,
    ACTIONS(101), 10,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_PERCENT,
      anon_sym_LT_PERCENT_,
      anon_sym_LT_QMARK_EQ,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ_EQ,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENTgraphql,
      anon_sym_LT_QMARKphp,
  [161] = 2,
    ACTIONS(107), 6,
      aux_sym_content_token1,
      anon_sym_LT_QMARK,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_PIPE,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ,
    ACTIONS(105), 10,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_PERCENT,
      anon_sym_LT_PERCENT_,
      anon_sym_LT_QMARK_EQ,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ_EQ,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENTgraphql,
      anon_sym_LT_QMARKphp,
  [182] = 2,
    ACTIONS(111), 6,
      aux_sym_content_token1,
      anon_sym_LT_QMARK,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_PIPE,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ,
    ACTIONS(109), 10,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_PERCENT,
      anon_sym_LT_PERCENT_,
      anon_sym_LT_QMARK_EQ,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ_EQ,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENTgraphql,
      anon_sym_LT_QMARKphp,
  [203] = 2,
    ACTIONS(115), 6,
      aux_sym_content_token1,
      anon_sym_LT_QMARK,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_PIPE,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ,
    ACTIONS(113), 10,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_PERCENT,
      anon_sym_LT_PERCENT_,
      anon_sym_LT_QMARK_EQ,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ_EQ,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENTgraphql,
      anon_sym_LT_QMARKphp,
  [224] = 2,
    ACTIONS(119), 6,
      aux_sym_content_token1,
      anon_sym_LT_QMARK,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_PIPE,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ,
    ACTIONS(117), 10,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_PERCENT,
      anon_sym_LT_PERCENT_,
      anon_sym_LT_QMARK_EQ,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ_EQ,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENTgraphql,
      anon_sym_LT_QMARKphp,
  [245] = 2,
    ACTIONS(123), 6,
      aux_sym_content_token1,
      anon_sym_LT_QMARK,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_PIPE,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ,
    ACTIONS(121), 10,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_PERCENT,
      anon_sym_LT_PERCENT_,
      anon_sym_LT_QMARK_EQ,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_PIPE_EQ_EQ,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENTgraphql,
      anon_sym_LT_QMARKphp,
  [266] = 5,
    ACTIONS(125), 1,
      aux_sym_code_token1,
    ACTIONS(127), 1,
      anon_sym_PERCENT_PERCENT_GT,
    STATE(19), 1,
      aux_sym_code_repeat1,
    STATE(27), 1,
      sym_code,
    ACTIONS(129), 4,
      anon_sym_PERCENT_GT,
      anon_sym_DASH_PERCENT_GT,
      anon_sym_QMARK_GT,
      anon_sym_EQ_PERCENT_GT,
  [285] = 5,
    ACTIONS(131), 1,
      aux_sym_code_token1,
    ACTIONS(133), 1,
      anon_sym_PERCENT_PERCENT_GT,
    STATE(21), 1,
      aux_sym_code_repeat1,
    STATE(31), 1,
      sym_code,
    ACTIONS(135), 3,
      anon_sym_PERCENT_GT,
      anon_sym_DASH_PERCENT_GT,
      anon_sym__PERCENT_GT,
  [303] = 4,
    ACTIONS(137), 1,
      aux_sym_code_token1,
    ACTIONS(139), 1,
      anon_sym_PERCENT_PERCENT_GT,
    STATE(20), 1,
      aux_sym_code_repeat1,
    ACTIONS(141), 4,
      anon_sym_PERCENT_GT,
      anon_sym_DASH_PERCENT_GT,
      anon_sym_QMARK_GT,
      anon_sym_EQ_PERCENT_GT,
  [319] = 4,
    ACTIONS(143), 1,
      aux_sym_code_token1,
    ACTIONS(146), 1,
      anon_sym_PERCENT_PERCENT_GT,
    STATE(20), 1,
      aux_sym_code_repeat1,
    ACTIONS(149), 4,
      anon_sym_PERCENT_GT,
      anon_sym_DASH_PERCENT_GT,
      anon_sym_QMARK_GT,
      anon_sym_EQ_PERCENT_GT,
  [335] = 4,
    ACTIONS(151), 1,
      aux_sym_code_token1,
    ACTIONS(153), 1,
      anon_sym_PERCENT_PERCENT_GT,
    STATE(22), 1,
      aux_sym_code_repeat1,
    ACTIONS(141), 3,
      anon_sym_PERCENT_GT,
      anon_sym_DASH_PERCENT_GT,
      anon_sym__PERCENT_GT,
  [350] = 4,
    ACTIONS(155), 1,
      aux_sym_code_token1,
    ACTIONS(158), 1,
      anon_sym_PERCENT_PERCENT_GT,
    STATE(22), 1,
      aux_sym_code_repeat1,
    ACTIONS(149), 3,
      anon_sym_PERCENT_GT,
      anon_sym_DASH_PERCENT_GT,
      anon_sym__PERCENT_GT,
  [365] = 5,
    ACTIONS(161), 1,
      aux_sym_code_token1,
    ACTIONS(163), 1,
      anon_sym_PERCENT_PERCENT_GT,
    ACTIONS(165), 1,
      anon_sym_PERCENT_GT,
    STATE(29), 1,
      aux_sym_code_repeat1,
    STATE(33), 1,
      sym_code,
  [381] = 5,
    ACTIONS(161), 1,
      aux_sym_code_token1,
    ACTIONS(163), 1,
      anon_sym_PERCENT_PERCENT_GT,
    ACTIONS(167), 1,
      anon_sym_PERCENT_GT,
    STATE(29), 1,
      aux_sym_code_repeat1,
    STATE(35), 1,
      sym_code,
  [397] = 5,
    ACTIONS(61), 1,
      aux_sym_code_token1,
    ACTIONS(169), 1,
      anon_sym_PERCENT_PERCENT_GT,
    ACTIONS(171), 1,
      anon_sym_QMARK_GT,
    STATE(26), 1,
      aux_sym_code_repeat1,
    STATE(32), 1,
      sym_code,
  [413] = 4,
    ACTIONS(141), 1,
      anon_sym_QMARK_GT,
    ACTIONS(173), 1,
      aux_sym_code_token1,
    ACTIONS(175), 1,
      anon_sym_PERCENT_PERCENT_GT,
    STATE(28), 1,
      aux_sym_code_repeat1,
  [426] = 1,
    ACTIONS(177), 4,
      anon_sym_PERCENT_GT,
      anon_sym_DASH_PERCENT_GT,
      anon_sym_QMARK_GT,
      anon_sym_EQ_PERCENT_GT,
  [433] = 4,
    ACTIONS(149), 1,
      anon_sym_QMARK_GT,
    ACTIONS(179), 1,
      aux_sym_code_token1,
    ACTIONS(182), 1,
      anon_sym_PERCENT_PERCENT_GT,
    STATE(28), 1,
      aux_sym_code_repeat1,
  [446] = 4,
    ACTIONS(141), 1,
      anon_sym_PERCENT_GT,
    ACTIONS(185), 1,
      aux_sym_code_token1,
    ACTIONS(187), 1,
      anon_sym_PERCENT_PERCENT_GT,
    STATE(30), 1,
      aux_sym_code_repeat1,
  [459] = 4,
    ACTIONS(149), 1,
      anon_sym_PERCENT_GT,
    ACTIONS(189), 1,
      aux_sym_code_token1,
    ACTIONS(192), 1,
      anon_sym_PERCENT_PERCENT_GT,
    STATE(30), 1,
      aux_sym_code_repeat1,
  [472] = 1,
    ACTIONS(195), 3,
      anon_sym_PERCENT_GT,
      anon_sym_DASH_PERCENT_GT,
      anon_sym__PERCENT_GT,
  [478] = 1,
    ACTIONS(197), 1,
      anon_sym_QMARK_GT,
  [482] = 1,
    ACTIONS(199), 1,
      anon_sym_PERCENT_GT,
  [486] = 1,
    ACTIONS(201), 1,
      ts_builtin_sym_end,
  [490] = 1,
    ACTIONS(203), 1,
      anon_sym_PERCENT_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 28,
  [SMALL_STATE(7)] = 56,
  [SMALL_STATE(8)] = 77,
  [SMALL_STATE(9)] = 98,
  [SMALL_STATE(10)] = 119,
  [SMALL_STATE(11)] = 140,
  [SMALL_STATE(12)] = 161,
  [SMALL_STATE(13)] = 182,
  [SMALL_STATE(14)] = 203,
  [SMALL_STATE(15)] = 224,
  [SMALL_STATE(16)] = 245,
  [SMALL_STATE(17)] = 266,
  [SMALL_STATE(18)] = 285,
  [SMALL_STATE(19)] = 303,
  [SMALL_STATE(20)] = 319,
  [SMALL_STATE(21)] = 335,
  [SMALL_STATE(22)] = 350,
  [SMALL_STATE(23)] = 365,
  [SMALL_STATE(24)] = 381,
  [SMALL_STATE(25)] = 397,
  [SMALL_STATE(26)] = 413,
  [SMALL_STATE(27)] = 426,
  [SMALL_STATE(28)] = 433,
  [SMALL_STATE(29)] = 446,
  [SMALL_STATE(30)] = 459,
  [SMALL_STATE(31)] = 472,
  [SMALL_STATE(32)] = 478,
  [SMALL_STATE(33)] = 482,
  [SMALL_STATE(34)] = 486,
  [SMALL_STATE(35)] = 490,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_directive, 3, 0, 1),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_directive, 3, 0, 1),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_graphql_directive, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_graphql_directive, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_directive, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_directive, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_php_directive, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_php_directive, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_directive, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_directive, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_php_directive, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_php_directive, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_directive, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_directive, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_graphql_directive, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_graphql_directive, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code, 1, 0, 0),
  [143] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [155] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [179] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [189] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [201] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_embedded_template(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
